
#Database
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/lista-de-tarefa?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: root
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
    show-sql: 'true'


#Redis - Cache
cache:
  type: redis
  redis:
    host: localhost
    port: 6379



webservice:
  via-cep:
    name: via-cep
    url: https://viacep.com.br/ws

#Log do feign
logging:
  level:
    com:
      lemoreiradev:
        listadetarefa:
          domain:
            client: DEBUG

#Server port
server:
  port: '8888'


#textos da home
home:
  textos:
    - titulo: Bem vindo
      subtitulo: Aqui voce pode criar tarefas
    - titulo: Cria diversas tarefas
      subtitulo: Seu dia-dia sob seu controle
    - titulo: Suas tarefas em um só lugar
      subtitulo: OK vamos lá


objTest:
  testOBJConfig:
    nome: teste config




demo:
  environment: prod
  hosts:
    - https://www.example1.com
    - https://www.example2.com